server:
  port: 8085
  servlet:
    context-path: /
  address: 0.0.0.0
spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3316/hmily_dubbo?useUnicode=true&characterEncoding=utf8
        username: root
        password:

mybatis:
  type-aliases-package: com.bruce.dubbo.common.dollar.entity
  config-location: classpath:mybatis/mybatis-config.xml

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: debug
        com.bruce.dubbo.bonuspoint: debug
        com.bruce.dubbo.lottery: debug
        com.bruce.dubbo: debug
    path: "./logs"

