server:
    port: 8570

spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password:
        url: jdbc:mysql://localhost:3306/mq?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true



mybatis:
    type-aliases-package: io.kimmking.kmq.entity
    mapper-locations: classpath:mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true

logging:
    level:
        io.kimmking.kmq.mapper: debug
